# Generated by Django 4.2.16 on 2024-11-21 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whiskeyshop', '0002_cart_cartitem_whiskey_delete_whiskeybrand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='whiskey',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='Whiskey',
        ),
    ]
