# Generated by Django 4.2.16 on 2024-11-21 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whiskeycellar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhiskeyBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='whiskey',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whiskeycellar.whiskeybrand'),
        ),
    ]
