# Generated by Django 4.2.16 on 2024-11-21 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whiskeycellar', '0002_whiskeybrand_alter_whiskey_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whiskeybrand',
            name='description',
        ),
    ]
