# Generated by Django 4.2.16 on 2024-11-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiskeycellar', '0003_remove_whiskeybrand_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='whiskey',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
