# Generated by Django 4.2.16 on 2024-11-28 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whiskeycellar', '0004_whiskey_abv_whiskey_amount_whiskey_distillery_and_more'),
        ('whiskeycellar', '0004_whiskey_stock'),
    ]

    operations = [
    ]
