# Generated by Django 4.2.16 on 2024-11-21 22:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='age',
        ),
        migrations.AddField(
            model_name='customuser',
            name='birthdate',
            field=models.DateField(default=datetime.date(1900, 1, 1)),
        ),
    ]
